SERVER_PORT: 8080

# POSTGRESQL
APP_POSTGRESQL_HOST: localhost
APP_POSTGRESQL_PORT: 5432
APP_POSTGRESQL_USER: sa
APP_POSTGRESQL_PASSWORD: password
APP_POSTGRESQL_NAME: main
APP_POSTGRESQL_SCHEMA: destiny_store