server:
  port: ${SERVER_PORT:8080}

spring:
  main:
    banner-mode: 'off'
  datasource:
    driver-class-name: org.postgresql.Driver
    url: >
      jdbc:postgresql://${APP_POSTGRESQL_HOST}:${APP_POSTGRESQL_PORT}/${APP_POSTGRESQL_NAME}?
      currentSchema={APP_POSTGRESQL_SCHEMA}"
    username: ${APP_POSTGRESQL_USER}
    password: ${APP_POSTGRESQL_PASSWORD}
  liquibase:
    change-log: db/migration/changelog.yml
    default-schema: ${APP_POSTGRESQL_SCHEMA}
    liquibase-schema: ${APP_POSTGRESQL_SCHEMA}

management:
  endpoints:
    enabled-by-default: false
    web:
      base-path: /
      exposure.include: info, health, prometheus, loggers
      path-mapping:
        prometheus: metrics
  endpoint:
    info:
      enabled: true
    health:
      enabled: true
      probes:
        enabled: true
    prometheus:
      enabled: true
    loggers:
      enabled: true

springdoc:
  show-actuator: true
  swagger-ui.path: /api/doc
  api-docs.path: /api
